version: '3'
networks:
  host:
    name: host
    external: true
services:
  app:
    build: 
      context: ../
      dockerfile: Dockerfile.dev
    network_mode: "host"
    volumes:
      - ..:/workspace:cached

    command: /bin/sh -c "while sleep 1000; do :; done"  


